### ISSUE TITLE
`smooth` inside `aes()` in your Spotify example

### ISSUE THREAD

**Issue by Z3tt** [davidsjoberg/ggbump#11]
Hi David,

Thanks for this great package! I am using it for the first time this very moment and it is really simple to use, a true extension without changing much of the ggplot2 experience.

In your wiki examples, namely the Spotify page, I think you should specify the `smooth` argument not inside the aesthetics: 

```
rk %>% 
  ggplot(aes(order, rank, color = tags, group = tags)) +
  geom_bump(smooth = 15, size = 2, alpha = 0.2) +
  scale_y_reverse() 
``` 

(Sorry, couldn't find any way to change+commit in a wiki.)

Cheers and keep up the good work,
Cédric

**Comment by davidsjoberg** [comment]
Hi Cédric!

Thanks for the comment! I made the spotify example in `ggbump` beta. Back then I had smooth as a mapping, but for the CRAN release i switched it to a "global" parameter since it made more sense :)

I'll fix the tutorial. Also, I wouldn't know either how to do a PR to a WIKI.

**Comment by davidsjoberg** [comment]
Fixed it! Thanks @Z3tt !
