### ISSUE TITLE
{dplyr} dependency

### ISSUE THREAD

**Issue by bobfromspace** [davidsjoberg/ggbump#5]
Hello, I am excited about this package but if it is loaded without {dplyr}, the plotting of lines is not possible. I get 'Computation failed in `stat_bump()`: could not find function "arrange"' warning and nothing is plotted.

**Comment by davidsjoberg** [comment]
Hello! Thanks for the pull request! I accepted it :)

**Comment by Kikse** [comment]
Hello, I have the same problem with the bump plot (Computation failed in `stat_bump()`:
could not find function "arrange).. Has there been an answer? I would be very interested if so.
Thanks,
Kerstin

**Comment by NaturalSelecta1** [comment]
Hello, 
I've come up against the same issue with the cran version. The github version of the package throws the error:
`Error in vars(-PANEL, -group, -x, -y, -r) : 
  could not find function "vars"`

Not sure if this is another dependency issue? Great package otherwise though!!

**Comment by davidsjoberg** [comment]
Thanks! I’ll look into it! Dplyr backend can make my packages break :/

Bästa hälsningar 
David
